//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cake.NUnitRetry.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cake.NUnitRetry.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;test-run id=&quot;2&quot; testcasecount=&quot;1&quot; result=&quot;Passed&quot; total=&quot;1&quot; passed=&quot;1&quot; failed=&quot;0&quot; inconclusive=&quot;0&quot; skipped=&quot;0&quot; asserts=&quot;0&quot; engine-version=&quot;3.10.0.0&quot; clr-version=&quot;4.0.30319.42000&quot; start-time=&quot;2019-10-10 21:24:14Z&quot; end-time=&quot;2019-10-10 21:24:15Z&quot; duration=&quot;0.510770&quot;&gt;
        ///  &lt;command-line&gt;&lt;![CDATA[nunit3-console.exe  ..\..\Debug\ProjectTests.dll --result=results-single-fail-fix.xml]]&gt;&lt;/command-line&gt;
        ///  &lt;test-suite type=&quot;Assembly&quot; id=&quot;0-1002&quot; name=&quot;ProjectTes [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FailureFixedResult {
            get {
                return ResourceManager.GetString("FailureFixedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;test-run id=&quot;2&quot; testcasecount=&quot;1&quot; result=&quot;Failed&quot; total=&quot;1&quot; passed=&quot;0&quot; failed=&quot;1&quot; inconclusive=&quot;0&quot; skipped=&quot;0&quot; asserts=&quot;0&quot; engine-version=&quot;3.10.0.0&quot; clr-version=&quot;4.0.30319.42000&quot; start-time=&quot;2019-10-10 21:07:31Z&quot; end-time=&quot;2019-10-10 21:07:31Z&quot; duration=&quot;0.539498&quot;&gt;
        ///  &lt;command-line&gt;&lt;![CDATA[nunit3-console.exe  ..\..\Debug\ProjectTests.dll --result=results.xml]]&gt;&lt;/command-line&gt;
        ///  &lt;test-suite type=&quot;Assembly&quot; id=&quot;0-1002&quot; name=&quot;ProjectTests.dll&quot; fullname [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FailureResult {
            get {
                return ResourceManager.GetString("FailureResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;test-run id=&quot;2&quot; testcasecount=&quot;2&quot; result=&quot;Passed&quot; total=&quot;2&quot; passed=&quot;2&quot; failed=&quot;0&quot; inconclusive=&quot;0&quot; skipped=&quot;0&quot; asserts=&quot;0&quot; engine-version=&quot;3.10.0.0&quot; clr-version=&quot;4.0.30319.42000&quot; start-time=&quot;2019-10-24 20:04:21Z&quot; end-time=&quot;2019-10-24 20:04:22Z&quot; duration=&quot;0.509627&quot;&gt;
        ///  &lt;command-line&gt;&lt;![CDATA[nunit3-console.exe  ../../Debug/ProjectTests.dll]]&gt;&lt;/command-line&gt;
        ///  &lt;test-suite type=&quot;Assembly&quot; id=&quot;0-1003&quot; name=&quot;ProjectTests.dll&quot; fullname=&quot;C:\Tests\ProjectTes [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TwoFailingTestsFixedResult {
            get {
                return ResourceManager.GetString("TwoFailingTestsFixedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;test-run id=&quot;2&quot; testcasecount=&quot;2&quot; result=&quot;Failed&quot; total=&quot;2&quot; passed=&quot;0&quot; failed=&quot;2&quot; inconclusive=&quot;0&quot; skipped=&quot;0&quot; asserts=&quot;0&quot; engine-version=&quot;3.10.0.0&quot; clr-version=&quot;4.0.30319.42000&quot; start-time=&quot;2019-10-24 19:13:10Z&quot; end-time=&quot;2019-10-24 19:13:11Z&quot; duration=&quot;0.542841&quot;&gt;
        ///  &lt;command-line&gt;&lt;![CDATA[nunit3-console.exe  ../../Debug/ProjectTests.dll]]&gt;&lt;/command-line&gt;
        ///  &lt;test-suite type=&quot;Assembly&quot; id=&quot;0-1003&quot; name=&quot;ProjectTests.dll&quot; fullname=&quot;C:\Tests\ProjectTes [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TwoFailingTestsResult {
            get {
                return ResourceManager.GetString("TwoFailingTestsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!--This file represents the results of running a test suite--&gt;
        ///&lt;test-results name=&quot;/home/charlie/Dev/NUnit/nunit-2.5/work/src/bin/Debug/tests/mock-assembly.dll&quot; total=&quot;21&quot; errors=&quot;1&quot; failures=&quot;1&quot; not-run=&quot;7&quot; inconclusive=&quot;1&quot; ignored=&quot;4&quot; skipped=&quot;0&quot; invalid=&quot;3&quot; date=&quot;2010-10-18&quot; time=&quot;13:23:35&quot;&gt;
        ///  &lt;environment nunit-version=&quot;2.5.8.0&quot; clr-version=&quot;2.0.50727.1433&quot; os-version=&quot;Unix 2.6.32.25&quot; platform=&quot;Unix&quot; cwd=&quot;/home/charlie/Dev/NUnit/nunit-2.5/work/s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlTestResults_NUnit2 {
            get {
                return ResourceManager.GetString("XmlTestResults_NUnit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;test-run id=&quot;2&quot; name=&quot;mock-assembly.dll&quot; fullname=&quot;D:\Dev\NUnit\nunit-3.0\work\bin\vs2008\Debug\mock-assembly.dll&quot; testcasecount=&quot;25&quot; result=&quot;Failed&quot; time=&quot;0.154&quot; total=&quot;18&quot; passed=&quot;12&quot; failed=&quot;2&quot; inconclusive=&quot;1&quot; skipped=&quot;3&quot; asserts=&quot;2&quot; run-date=&quot;2011-07-26&quot; start-time=&quot;11:34:27&quot;&gt;
        ///  &lt;environment nunit-version=&quot;1.0.0.0&quot; clr-version=&quot;2.0.50727.4961&quot; os-version=&quot;Microsoft Windows NT 6.1.7600.0&quot; platform=&quot;Win32NT&quot; cwd=&quot;D:\Dev\NUnit\nunit-3.0\work\bin\vs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlTestResults_NUnit3 {
            get {
                return ResourceManager.GetString("XmlTestResults_NUnit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;test-run id=&quot;2&quot; name=&quot;mock-assembly.dll&quot; fullname=&quot;D:\Dev\NUnit\nunit-3.0\work\bin\vs2008\Debug\mock-assembly.dll&quot; testcasecount=&quot;25&quot; result=&quot;Failed&quot; time=&quot;0.154&quot; total=&quot;18&quot; passed=&quot;12&quot; failed=&quot;2&quot; inconclusive=&quot;1&quot; skipped=&quot;3&quot; asserts=&quot;2&quot; run-date=&quot;2011-07-26&quot; start-time=&quot;11:34:27&quot;&gt;
        ///  &lt;environment nunit-version=&quot;1.0.0.0&quot; clr-version=&quot;2.0.50727.4961&quot; os-version=&quot;Microsoft Windows NT 6.1.7600.0&quot; platform=&quot;Win32NT&quot; cwd=&quot;D:\Dev\NUnit\nunit-3.0\work\bin\vs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlTestResults_NUnit3_DuplicateTestName {
            get {
                return ResourceManager.GetString("XmlTestResults_NUnit3_DuplicateTestName", resourceCulture);
            }
        }
    }
}
